# https://gist.github.com/System-Glitch/c53ca30a579dc60c7ea6333a40caec2c
upstream php {
    server php:9000;
}

server {
    listen 8080;
    listen [::]:8080;
    server_name digitick.local;
    root /var/www/html/public;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }   
}
