FROM php:8.3-cli

# Install PHP extensions
RUN docker-php-ext-install mysqli pdo_mysql

# Install xdebug via pecl
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port=9000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Node.js via nvm
ENV NODE_VERSION=16.13.0
ENV NVM_DIR=/root/.nvm
RUN apt-get update \
    && apt-get install -y curl ca-certificates bash \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION} \
    && . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION} \
    && . "$NVM_DIR/nvm.sh" && nvm use default \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="$NVM_DIR/versions/node/v${NODE_VERSION}/bin/:${PATH}"

# Verify versions
RUN php -v && php -m | grep mysqli && node -v && npm -v

CMD ["php", "-a"]
